# Generated by Django 2.1.7 on 2019-03-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False)),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=100)),
                ('designer', models.CharField(max_length=100)),
                ('designer_url', models.URLField()),
                ('twitter', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='websites')),
                ('image2', models.ImageField(upload_to='websites')),
                ('image3', models.ImageField(upload_to='websites')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
